### ISSUE TITLE
add link to https://www.ovn.org/en/ in repo

### ISSUE THREAD

**Issue by pwright** [ovn-org/ovn-website#12] opened 2020-07-15 13:04 UTC
trying to learn more about ovn, and came across this repo. 
Add link to repo about section would help newbies (and easy to do)

![image](https://user-images.githubusercontent.com/5154224/87548193-0d66d280-c6a4-11ea-9bb3-fc1ac037d8a7.png)

**Comment by flavio-fernandes** [comment] 2021-03-22 22:11
@pwright could you make a pull request with what you are describing? I am not 100% I understand what you are looking for with this issue.

**Comment by pwright** [comment] 2021-03-23 08:51
it's the github settings for the repo, add the url as per:
![image](https://user-images.githubusercontent.com/5154224/112118941-c9be5400-8bb4-11eb-96a8-ae9c40df92a1.png)

You can see the result at https://github.com/pwright/ovn-website

![image](https://user-images.githubusercontent.com/5154224/112119065-ece90380-8bb4-11eb-910e-28e7f6f6393c.png)

**Comment by putnopvut** [comment] 2021-03-23 12:31
Hi Paul, thanks for the suggestion. I tried to update the website but apparently don't have permission.

@mangelajo, @justinpettit, @dcbw : I think you guys have write access to repository details. Can one of you update the website link on this repo as Paul has demonstrated above? Thanks!

**Comment by blp** [comment] 2021-03-23 16:32
@putnopvut I added you to the appropriate team.

**Comment by putnopvut** [comment] 2021-03-23 20:21
Thanks @blp. I can confirm that I was able to update the repo info to include the website link.

Closing this since it is now fixed.

**Closed by putnopvut** 2021-03-23 20:21 UTC
